version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: defaultuser
      POSTGRES_PASSWORD: defaultpassword
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
